name: CI for Docker App with Selenium Tests

on:
  push:
    branches: []

jobs:
  Selenium-Tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Install Docker Compose (download the standalone binary)
    - name: Install Docker Compose
      env:
        DOCKER_COMPOSE_VERSION: latest
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION:-$LATEST_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Step 4: Set up Python environment (for running Selenium tests)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest

    # Step 5: Create the necessary environment and build the Docker container
    - name: Run docker-compose up --build
      run: |
        docker-compose up --build -d
    
    # Step 6: Wait for the app to be ready (you might need to adjust this sleep time)
    - name: Wait for app to be ready
      run: |
        timeout=60
        while ! curl -s http://localhost:5000/health; do
          if [ $timeout -le 0 ]; then
            echo "Timed out waiting for app to be ready"
            exit 1
          fi
          echo "Waiting for app to be ready..."
          sleep 5
          timeout=$((timeout - 5))
        done  # Adjust this based on the time your app needs to be up and running

    # Step 7: Run Selenium tests
    - name: Run Selenium tests
      run: |
        pytest tests/  # Adjust this to your test path

    # Step 8: Tear down the Docker containers after testing
    - name: Tear down Docker containers
      run: |
        docker-compose down