name: Python package

on:
  push:
    branches: []

env:
  GIT_HUB_KEY: ${{ vars.GIT_HUB_KEY }}


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run tests
      run: |
        python -m unittest discover -s scr/tests -p 'test_*.py'