name: CI for Docker App with Selenium Tests

on:
  push:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build and run the application using Docker Compose
    - name: Build and run app with Docker Compose
      run: |
        docker-compose up --build -d

    # Step 4: Wait for Docker app to be ready
    - name: Wait for the app to be ready
      run: |
        # Retry waiting for the application to start (replace with your URL)
        for i in `seq 1 10`; do
          curl http://localhost:5000 && break
          sleep 5
        done

    # Step 5: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 6: Install dependencies
    - name: Install dependencies
      run: |
        pip install selenium pytest

    # Step 7: Run the tests using pytest
    - name: Run UI tests
      run: |
        pytest test_ui.py --maxfail=1 --disable-warnings

    # Step 8: Tear down Docker Compose after the tests
    - name: Tear down Docker Compose
      run: |
        docker-compose down